[package]
org = "ballerina"
name = "math"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../math-native/build/libs/math-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "math"
version = "@project.version@"
